version: '2'
services:
  web:
    container_name: web
    restart: always
    image: nginx:alpine
    volumes:
      - ./app:/app
      - ./conf/nginx.vh.conf:/etc/nginx/conf.d/default.conf
    ports: [ '80:80' ]
  php:
    container_name: php
    image: imkulikov/docker-php7
    restart: always
    volumes:
      - ./app:/app